### ISSUE TITLE
Possible Oregen/Config Bug

### ISSUE THREAD

**Issue by Watschman** [imrgr/rise-of-the-pack#3]
Pack Version: 1.2.0
Java Version: 8-144 (64bit)
Additional Mods Added: Dimensionloader, Fullscreen Windowed (Borderless) for Minecraft
Type of issue: Bug
-------------------------
Hello, 
I am currently playing and streaming your Modpack. 
I noticed that Immersive Engineering is telling about Uranium Ore, but no Uranium Ore could be found after hours of mining.
Looking at the config File, I saw that the spawning of Uranium Ore is disabled in the immersiveengineering.cfg (Vein Size set to 0).
![oreuranium](https://user-images.githubusercontent.com/13834558/31865412-06404aa0-b76f-11e7-92f1-b96075d216ba.PNG)
I was wondering whether or not that was intentional or a mistake, so that it is currently only obtainable via the Void Ore Miner (if JEI is to be believed, I am not quite at that point of the Game yet).
So long, 
Watschman.

**Comment by imrgr** [comment]
Hello Watschman,
I did indeed disable the generation of Uranium Ore because as far as I know, it is yet unused in Immersive Engineering. That is unless you are using it for decoration. I can definitely see the merit in using it for decorative purposes.

Please tell me, am I wrong about it not having a functional purpose within Immersive Engineering. Even if it does not, do you think I should add it back into generation so that players may use it as a decorative block before they get to the point of having Void Miners? I ask these questions with the utmost sincerity, for as you may know, this is my first public modpack. I greatly appreciate any feedback you are willing to give.

**Comment by Watschman** [comment]
It can be used as a heat source for the Thermoelectric Generator(From the looks of it far better than regular old Lava), at least if the Engineer's Manual is to be believed.

**Comment by imrgr** [comment]
I see. Let me play around with it. I'm going to add it back into generation. I'm going to base its rarity on how much more powerful it is than lava, in this case. Thank you for your help.
