### ISSUE TITLE
Crash at the start of the modpack load

### ISSUE THREAD

**Issue by volcano010** [imrgr/rise-of-the-pack#6]
Rise of the Pack 1.3.1
I cant play because of this problem:

[crash-2017-11-02_19.51.35-client.txt](https://github.com/imrgr/rise-of-the-pack/files/1439639/crash-2017-11-02_19.51.35-client.txt)

Thanks.

**Comment by Watschman** [comment]
Seems to be related to the newer Forge Version, downgrading to Forge 2522 may fix the issue rwtema/extrautilities#1736

Also: are you using a custom launcher? Because the Pack has Forge 2522, if the json manifest is to be believed and your client was running Forge 2528.
![crash](https://user-images.githubusercontent.com/13834558/32371718-3e1a2d02-c092-11e7-9119-309eb17d718b.png)

**Comment by volcano010** [comment]
Thanks for answering, I'll have to try that method then.

**Comment by imrgr** [comment]
Yes, any forge version above 2522, gives the same error. "java.lang.ClassNotFoundException: net.minecraftforge.client.model.ItemLayerModel$BakedItemModel" Downgrading to 2522 should fix the issue.

volcano010, thanks for the post!

Watschman, thanks for the quick help!
